register(GRAMPLET,
         id = "Dates",
         name = _("Dates"),
         description = _("Dates"),
         status = STABLE,
         version = '0.0.15',
         gramps_target_version = '5.1',
         fname = "Dates.py",
         gramplet = 'Dates',
         height = 375,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet_title = _("Dates"),
         help_url="Dates gramplet",
         include_in_listing = True,
         navtypes=["Event"],
        )
